CATEGORY_SELECTION = "Select which to search by 1) users, 2) organisations, 3) tickets: "
CATEGORY_SELECTION_TRY_AGAIN = "Input was not a number between 1-3, please try again."
SEARCH_TERM = "Search by term: "
SEARCH_VALUE = "Enter a value: "
TERM_INVALID = "The term you have entered does not exist, please try again."
SEARCHING = "Searching..."
FINISHED_SEARCHING = "Finished searching."
NO_RESULTS = "Cannot find any results"
RANGE_ERROR = "Please enter a number between 1 and 3"

USERS = "users"
ORGS = "organisations"
TICKETS = "tickets"
TERMS = "terms"
